<a href="https://colab.research.google.com/github/DanL1L/Scrape/blob/main/0_nowcast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import os
import pandas as pd
import json
import glob
import re
import numpy as np

os.chdir(r'/content/sample_data')

In [18]:
# import map
map = pd.read_excel(r'/content/sample_data/map.xlsx')
map['product_sku'] = map['product_sku'].astype(str)
map['code'] = map['code'].apply(lambda x: x[:3] if pd.notna(x) and len(x) > 3 else x)    # categories on the same level F011 -> F01
map = map[map['confidence'] >= 90]
map

,product_sku,product_name,code,category_name,confidence
0,194813,BOSTAVAN Dry white wine DOR Feteasca Alba & Ch...,F15,....wine,100
1,2560,CRICOVA Dry red wine PRESTIGE Cabernet Sauvign...,F15,....wine,100
2,278829,RADACINI Sparkling Wine white semidry750 ml,F15,....wine,100
3,3238,CALARASI Strong alcoholic drink DUMBRAVA 500ml,F15,..Alcoholic drinks,95
4,13256,CALARASI Divin LEGENDA 3 years 500ml,F15,..Alcoholic drinks,95
...,...,...,...,...,...
9643,239078,KAMIS Ground Nutmeg 15g,F16,..Other foodstuffs not classified in other cat...,95
9644,239016,KAMIS Cinnamon Sticks 17g,F16,..Other foodstuffs not classified in other cat...,95
9645,488467,KAMIS Vanilla pod 1 pc,F16,..Other foodstuffs not classified in other cat...,95
9646,2010868,KAMIS Ground cardamom 10g,F16,..Other foodstuffs not classified in other cat...,95
9647,416666,"SPORTS Badminton Shuttlecock Set (Yellow, 3 pcs.)",N13,"..Equipment for sport, camping and open-air re...",100

In [20]:
# import weights
weights = pd.read_excel(r'/content/sample_data/weight_data.xlsx', sheet_name = 'w_m')
weights['date'] = pd.to_datetime(weights['date'])
weights = weights.melt(id_vars=['date'], var_name='code', value_name='weight')   # transform data from wide to long
weights = weights.rename(columns={"date": "month"})
weights

           month code    weight
0     2015-01-01    T  1.000000
1     2015-02-01    T  1.000000
2     2015-03-01    T  1.000000
3     2015-04-01    T  1.000000
4     2015-05-01    T  1.000000
...          ...  ...       ...
14659 2027-08-01  S12  0.000641
14660 2027-09-01  S12  0.000641
14661 2027-10-01  S12  0.000641
14662 2027-11-01  S12  0.000641
14663 2027-12-01  S12  0.000641

[14664 rows x 3 columns]

In [23]:
# find all .json files in folder, glob.glob() finds all data paths
files = glob.glob(os.path.join(r'/content/sample_data/Linella', '*.json'))

In [24]:
scrape_data = []

for file in files:
    # date from name e.g. linella_scrape_20260402.json
    match = re.search(r'\d{8}', os.path.basename(file))
    date = match.group(0)

    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)

        for item in data:
            # if there is discount price take discount price, otherwise take product_price
            d_price = item.get('discount_price')
            p_price = item.get('product_price')
            final_price = d_price if d_price else p_price

            scrape_data.append({
                'date': date,
                'product_sku': item.get('product_sku'),
                'price': final_price
            })

In [ ]:
scrape_data

[{'date': '20260402', 'product_sku': '2737', 'price': '149.00'},
 {'date': '20260402', 'product_sku': '2570', 'price': '175.00'},
 {'date': '20260402', 'product_sku': '15438', 'price': '509.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '187848', 'price': '309.00'},
 {'date': '20260402', 'product_sku': '40229', 'price': '79.90'},
 {'date': '20260402', 'product_sku': '2680', 'price': '149.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '194813', 'price': '95.30'},
 {'date': '20260402', 'product_sku': '2511', 'price': '245.00'},
 {'date': '20260402', 'product_sku': '2513', 'price': '275.00'},
 {'date': '20260402', 'product_sku': '120168', 'price': '279.00'},
 {'date': '20260402', 'product_sku': '2908', 'price': '235.00'},
 {'date': '20260402', 'product_sku': '2907', 'price': '175.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '3154', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '3158', 'price': '109.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '13209', 'price': '365.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '52438', 'price': '345.00'},
 {'date': '20260402', 'product_sku': '74313', 'price': '79.90'},
 {'date': '20260402', 'product_sku': '57653', 'price': '409.00'},
 {'date': '20260402', 'product_sku': '199194', 'price': '105.00'},
 {'date': '20260402', 'product_sku': '199195', 'price': '145.00'},
 {'date': '20260402', 'product_sku': '199739', 'price': '299.00'},
 {'date': '20260402', 'product_sku': '199737', 'price': '439.00'},
 {'date': '20260402', 'product_sku': '184207', 'price': '84.90'},
 {'date': '20260402', 'product_sku': '184209', 'price': '84.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '196353', 'price': '84.90'},
 {'date': '20260402', 'product_sku': '128213', 'price': '89.90'},
 {'date': '20260402', 'product_sku': '2831', 'price': '82.90'},
 {'date': '20260402', 'product_sku': '77278', 'price': '83.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '128152', 'price': '86.90'},
 {'date': '20260402', 'product_sku': '196365', 'price': '245.00'},
 {'date': '20260402', 'product_sku': '128150', 'price': '86.90'},
 {'date': '20260402', 'product_sku': '196366', 'price': '99.90'},
 {'date': '20260402', 'product_sku': '74309', 'price': '73.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '278211', 'price': '25.50'},
 {'date': '20260402', 'product_sku': '2549', 'price': '54.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '2556', 'price': '142.00'},
 {'date': '20260402', 'product_sku': '74315', 'price': '79.90'},
 {'date': '20260402', 'product_sku': '2560', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '2627', 'price': '142.00'},
 {'date': '20260402', 'product_sku': '2564', 'price': '37.90'},
 {'date': '20260402', 'product_sku': '2685', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '58036', 'price': '175.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '2711', 'price': '44.90'},
 {'date': '20260402', 'product_sku': '2786', 'price': '47.90'},
 {'date': '20260402', 'product_sku': '2792', 'price': '239.00'},
 {'date': '20260402', 'product_sku': '2804', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '2795', 'price': '85.90'},
 {'date': '20260402', 'product_sku': '2798', 'price': '145.00'},
 {'date': '20260402', 'product_sku': '15639', 'price': '49.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '74310', 'price': '73.90'},
 {'date': '20260402', 'product_sku': '139970', 'price': '50.90'},
 {'date': '20260402', 'product_sku': '40224', 'price': '87.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '77556', 'price': '99.90'},
 {'date': '20260402', 'product_sku': '58038', 'price': '206.00'},
 {'date': '20260402', 'product_sku': '139972', 'price': '50.90'},
 {'date': '20260402', 'product_sku': '128014', 'price': '118.00'},
 {'date': '20260402', 'product_sku': '139971', 'price': '50.90'},
 {'date': '20260402', 'product_sku': '161926', 'price': '89.90'},
 {'date': '20260402', 'product_sku': '166212', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '208647', 'price': '145.00'},
 {'date': '20260402', 'product_sku': '167851', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '128215', 'price': '215.00'},
 {'date': '20260402', 'product_sku': '2889', 'price': '299.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '208652', 'price': '199.00'},
 {'date': '20260402', 'product_sku': '52260', 'price': '139.00'},
 {'date': '20260402', 'product_sku': '218028', 'price': '89.90'},
 {'date': '20260402', 'product_sku': '52257', 'price': '125.00'},
 {'date': '20260402', 'product_sku': '52265', 'price': '325.00'},
 {'date': '20260402', 'product_sku': '52247', 'price': '415.00'},
 {'date': '20260402', 'product_sku': '170626', 'price': '169.00'},
 {'date': '20260402', 'product_sku': '78685', 'price': '159.00'},
 {'date': '20260402', 'product_sku': '128174', 'price': '249.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '166604', 'price': '64.90'},
 {'date': '20260402', 'product_sku': '170627', 'price': '154.00'},
 {'date': '20260402', 'product_sku': '170633', 'price': '169.00'},
 {'date': '20260402', 'product_sku': '170636', 'price': '154.00'},
 {'date': '20260402', 'product_sku': '2611', 'price': '165.00'},
 {'date': '20260402', 'product_sku': '170634', 'price': '169.00'},
 {'date': '20260402', 'product_sku': '170637', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '170640', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '170641', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '170638', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '170639', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '170645', 'price': '87.90'},
 {'date': '20260402', 'product_sku': '170646', 'price': '87.90'},
 {'date': '20260402', 'product_sku': '170642', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '173653', 'price': '87.90'},
 {'date': '20260402', 'product_sku': '128214', 'price': '149.00'},
 {'date': '20260402', 'product_sku': '170643', 'price': '90.90'},
 {'date': '20260402', 'product_sku': '173651', 'price': '87.90'},
 {'date': '20260402', 'product_sku': '194570', 'price': '154.00'},
 {'date': '20260402', 'product_sku': '207587', 'price': '169.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '215202', 'price': '154.00'},
 {'date': '20260402', 'product_sku': '216513', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '216514', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '216515', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '278829', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '3009', 'price': '105.00'},
 {'date': '20260402', 'product_sku': '289424', 'price': '115.00'},
 {'date': '20260402', 'product_sku': '3055', 'price': '109.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '20483', 'price': '77.90'},
 {'date': '20260402', 'product_sku': '48815', 'price': '40.90'},
 {'date': '20260402', 'product_sku': '22651', 'price': '93.90'},
 {'date': '20260402', 'product_sku': '121359', 'price': '56.90'},
 {'date': '20260402', 'product_sku': '163978', 'price': '199.00'},
 {'date': '20260402', 'product_sku': '40217', 'price': '109.00'},
 {'date': '20260402', 'product_sku': '3238', 'price': '99.90'},
 {'date': '20260402', 'product_sku': '121356', 'price': '129.00'},
 {'date': '20260402', 'product_sku': '163979', 'price': '45.90'},
 {'date': '20260402', 'product_sku': '3206', 'price': '51.90'},
 {'date': '20260402', 'product_sku': '3239', 'price': '78.90'},
 {'date': '20260402', 'product_sku': '13258', 'price': '219.00'},
 {'date': '20260402', 'product_sku': '13256', 'price': '119.00'},
 {'date': '20260402', 'product_sku': '3267', 'price': '145.00'},
 {'date': '20260402', 'product_sku': '257280', 'price': '159.00'},
 {'date': '20260402', 'product_sku': '40220', 'price': '109.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '3252', 'price': '225.00'},
 {'date': '20260402', 'product_sku': '44174', 'price': '79.90'},
 {'date': '20260402', 'product_sku': '110181', 'price': '144.00'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '3258', 'price': '189.00'},
 {'date': '20260402', 'product_sku': '168268', 'price': '216.00'},
 {'date': '20260402', 'product_sku': '3255', 'price': '235.00'},
 {'date': '20260402', 'product_sku': '110569', 'price': '335.00'},
 {'date': '20260402', 'product_sku': '125318', 'price': '74.90'},
 {'date': '20260402', 'product_sku': '277788', 'price': '69.90'},
 {'date': '20260402', 'product_sku': '277447', 'price': '89.00'},
 {'date': '20260402', 'product_sku': '117318', 'price': '169.00'},
 {'date': '20260402', 'product_sku': '263624', 'price': '125.00'},
 {'date': '20260402', 'product_sku': '117320', 'price': '125.00'},
 {'date': '20260402', 'product_sku': '277789', 'price': '69.90'},
 {'date': '20260402', 'product_sku': '73829', 'price': '54.50'},
 {'date': '20260402', 'product_sku': '66925', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '32373', 'price': '28.20'},
 {'date': '20260402', 'product_sku': '163341', 'price': '62.40'},
 {'date': '20260402', 'product_sku': '110555', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '21734', 'price': '26.90'},
 {'date': '20260402', 'product_sku': '32173', 'price': '16.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '56712', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '22255', 'price': '16.90'},
 {'date': '20260402', 'product_sku': '77514', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '45060', 'price': '30.00'},
 {'date': '20260402', 'product_sku': '75029', 'price': '21.95'},
 {'date': '20260402', 'product_sku': '56713', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '132283', 'price': '52.90'},
 {'date': '20260402', 'product_sku': '117417', 'price': '14.90'},
 {'date': '20260402', 'product_sku': '132281', 'price': '43.90'},
 {'date': '20260402', 'product_sku': '114553', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '132280', 'price': '43.90'},
 {'date': '20260402', 'product_sku': '265903', 'price': '58.00'},
 {'date': '20260402', 'product_sku': '132282', 'price': '38.90'},
 {'date': '20260402', 'product_sku': '264979', 'price': '34.90'},
 {'date': '20260402', 'product_sku': '274074', 'price': '24.90'},
 {'date': '20260402', 'product_sku': '220133', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '276438', 'price': '26.50'},
 {'date': '20260402', 'product_sku': '132284', 'price': '52.90'},
 {'date': '20260402', 'product_sku': '276437', 'price': '26.50'},
 {'date': '20260402', 'product_sku': '44188', 'price': '36.90'},
 {'date': '20260402', 'product_sku': '169180', 'price': '33.90'},
 {'date': '20260402', 'product_sku': '169185', 'price': '33.90'},
 {'date': '20260402', 'product_sku': '2340', 'price': '17.90'},
 {'date': '20260402', 'product_sku': '2337', 'price': '20.50'},
 {'date': '20260402', 'product_sku': '169184', 'price': '33.90'},
 {'date': '20260402', 'product_sku': '2346', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '2341', 'price': '24.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '2347', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '3645', 'price': '26.90'},
 {'date': '20260402', 'product_sku': '124792', 'price': '48.90'},
 {'date': '20260402', 'product_sku': '2332', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '2385', 'price': '30.90'},
 {'date': '20260402', 'product_sku': '196361', 'price': '27.90'},
 {'date': '20260402', 'product_sku': '124797', 'price': '48.90'},
 {'date': '20260402', 'product_sku': '140556', 'price': '36.90'},
 {'date': '20260402', 'product_sku': '2331', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '2326', 'price': '40.90'},
 {'date': '20260402', 'product_sku': '126058', 'price': '71.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '2422', 'price': '21.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '126059', 'price': '39.90'},
 {'date': '20260402', 'product_sku': '127079', 'price': '27.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '107583', 'price': '34.40'},
 {'date': '20260402', 'product_sku': '64756', 'price': '59.90'},
 {'date': '20260402', 'product_sku': '256802', 'price': '39.90'},
 {'date': '20260402', 'product_sku': '64755', 'price': '49.90'},
 {'date': '20260402', 'product_sku': '113553', 'price': '48.60'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '31926', 'price': '29.30'},
 {'date': '20260402', 'product_sku': '72186', 'price': '79.90'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '200593', 'price': '70.90'},
 {'date': '20260402', 'product_sku': '188054', 'price': '42.70'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '3360', 'price': '19.70'},
 {'date': '20260402', 'product_sku': '3367', 'price': '12.90'},
 {'date': '20260402', 'product_sku': '3472', 'price': '13.00'},
 {'date': '20260402', 'product_sku': '3366', 'price': '22.80'},
 {'date': '20260402', 'product_sku': '3359', 'price': '12.90'},
 {'date': '20260402', 'product_sku': '3483', 'price': '15.50'},
 {'date': '20260402', 'product_sku': '3551', 'price': '15.50'},
 {'date': '20260402', 'product_sku': '13264', 'price': '19.70'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '215637', 'price': '18.50'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '124543', 'price': '32.50'},
 {'date': '20260402', 'product_sku': '199450', 'price': '28.50'},
 {'date': '20260402', 'product_sku': '124523', 'price': '32.50'},
 {'date': '20260402', 'product_sku': '216681', 'price': '28.50'},
 {'date': '20260402', 'product_sku': '124524', 'price': '32.50'},
 {'date': '20260402', 'product_sku': '199449', 'price': '28.50'},
 {'date': '20260402', 'product_sku': '199454', 'price': '28.50'},
 {'date': '20260402', 'product_sku': '179251', 'price': '14.90'},
 {'date': '20260402', 'product_sku': '264172', 'price': '14.50'},
 {'date': '20260402', 'product_sku': '23655', 'price': '42.90'},
 {'date': '20260402', 'product_sku': '26243', 'price': '19.90'},
 {'date': '20260402', 'product_sku': '23654', 'price': '42.90'},
 {'date': '20260402', 'product_sku': '45759', 'price': '42.90'},
 {'date': '20260402', 'product_sku': '54360', 'price': '14.95'},
 {'date': '20260402', 'product_sku': '54351', 'price': '10.90'},
 {'date': '20260402', 'product_sku': '54361', 'price': '14.95'},
 {'date': '20260402', 'product_sku': '109882', 'price': '18.20'},
 {'date': '20260402', 'product_sku': '109876', 'price': '18.20'},
 {'date': '20260402', 'product_sku': '56826', 'price': '18.80'},
 {'date': '20260402', 'product_sku': '109879', 'price': '18.20'},
 {'date': '20260402', 'product_sku': '263095', 'price': '18.80'},
 {'date': '20260402', 'product_sku': '202757', 'price': '12.75'},
 {'date': '20260402', 'product_sku': '272285', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '272284', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '2137', 'price': '44.50'},
 {'date': '20260402', 'product_sku': '2132', 'price': '23.50'},
 {'date': '20260402', 'product_sku': '2134', 'price': '39.90'},
 {'date': '20260402', 'product_sku': '2136', 'price': '23.50'},
 {'date': '20260402', 'product_sku': '2133', 'price': '23.50'},
 {'date': '20260402', 'product_sku': '202759', 'price': '19.90'},
 {'date': '20260402', 'product_sku': '2140', 'price': '17.30'},
 {'date': '20260402', 'product_sku': '2141', 'price': '44.50'},
 {'date': '20260402', 'product_sku': '2168', 'price': '22.50'},
 {'date': '20260402', 'product_sku': '2174', 'price': '26.50'},
 {'date': '20260402', 'product_sku': '29072', 'price': '19.95'},
 {'date': '20260402', 'product_sku': '34109', 'price': '44.50'},
 {'date': '20260402', 'product_sku': '2175', 'price': '22.50'},
 {'date': '20260402', 'product_sku': '39825', 'price': '5.50'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '39828', 'price': '6.40'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '39827', 'price': '7.30'},
 {'date': '20260402', 'product_sku': '39826', 'price': '7.30'},
 {'date': '20260402', 'product_sku': '39829', 'price': '6.00'},
 {'date': '20260402', 'product_sku': '3431', 'price': '32.90'},
 {'date': '20260402', 'product_sku': '54359', 'price': '10.90'},
 {'date': '20260402', 'product_sku': '44145', 'price': '50.25'},
 {'date': '20260402', 'product_sku': '279905', 'price': '52.50'},
 {'date': '20260402', 'product_sku': '131722', 'price': '5.50'},
 {'date': '20260402', 'product_sku': '203684', 'price': '17.30'},
 {'date': '20260402', 'product_sku': '2178', 'price': '42.20'},
 {'date': '20260402', 'product_sku': '219236', 'price': '17.30'},
 {'date': '20260402', 'product_sku': '2198', 'price': '25.00'},
 {'date': '20260402', 'product_sku': '2184', 'price': '25.00'},
 {'date': '20260402', 'product_sku': '2203', 'price': '24.70'},
 {'date': '20260402', 'product_sku': '126464', 'price': '34.90'},
 {'date': '20260402', 'product_sku': '225068', 'price': '39.90'},
 {'date': '20260402', 'product_sku': '2283', 'price': '54.20'},
 {'date': '20260402', 'product_sku': '2289', 'price': '42.20'},
 {'date': '20260402', 'product_sku': '203265', 'price': '35.20'},
 {'date': '20260402', 'product_sku': '3439', 'price': '16.40'},
 {'date': '20260402', 'product_sku': '3335', 'price': '28.10'},
 {'date': '20260402', 'product_sku': '66616', 'price': '42.20'},
 {'date': '20260402', 'product_sku': None, 'price': None},
 {'date': '20260402', 'product_sku': '3445', 'price': '16.40'},
 {'date': '20260402', 'product_sku': '3443', 'price': '16.40'},
 {'date': '20260402', 'product_sku': '216347', 'price': '25.00'},
 {'date': '20260402', 'product_sku': '264884', 'price': '24.70'},
 {'date': '20260402', 'product_sku': '264885', 'price': '24.70'},
 {'date': '20260402', 'product_sku': '264886', 'price': '27.50'},
 {'date': '20260402', 'product_sku': '129656', 'price': '25.50'},
 {'date': '20260402', 'product_sku': '264881', 'price': '26.90'},
 {'date': '20260402', 'product_sku': '239420', 'price': '25.50'},
 {'date': '20260402', 'product_sku': '264887', 'price': '26.90'},
 {'date': '20260402', 'product_sku': '264894', 'price': '6.90'},
 {'date': '20260402', 'product_sku': '15424', 'price': '25.50'},
 {'date': '20260402', 'product_sku': '3373', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '56773', 'price': '25.90'},
 {'date': '20260402', 'product_sku': '285468', 'price': '29.90'},
 {'date': '20260402', 'product_sku': '258778', 'price': '24.50'},
 {'date': '20260402', 'product_sku': '258779', 'price': '24.50'},

In [25]:
# from list to dataframe
scrape_data_df = pd.DataFrame(scrape_data)
scrape_data_df['price'] = pd.to_numeric(scrape_data_df['price'], errors='coerce')
scrape_data_df['date'] = pd.to_datetime(scrape_data_df['date'], format='%Y%m%d')
scrape_data_df['product_sku'] = scrape_data_df['product_sku'].astype(str)
scrape_data_df

             date product_sku  price
0      2026-04-07       15438  509.0
1      2026-04-07        None    NaN
2      2026-04-07        2680  175.0
3      2026-04-07      128213   89.9
4      2026-04-07        None    NaN
...           ...         ...    ...
569599 2026-05-29        None    NaN
569600 2026-05-29        None    NaN
569601 2026-05-29        None    NaN
569602 2026-05-29        None    NaN
569603 2026-05-29        None    NaN

[569604 rows x 3 columns]

In [26]:
scrape_map = pd.merge(scrape_data_df, map[['code', 'product_sku']], how='left', on='product_sku')
scrape_map.dropna(subset=['code'], inplace=True)
scrape_map

             date product_sku  price code
0      2026-04-07       15438  509.0  F15
3      2026-04-07      128213   89.9  F15
5      2026-04-07       58038  206.0  F15
14     2026-04-07       74310   73.9  F15
16     2026-04-07        2908  235.0  F15
...           ...         ...    ...  ...
569330 2026-05-29      488467  199.0  F16
569331 2026-05-29      239022   74.9  F16
569333 2026-05-29      239016   49.9  F16
569337 2026-05-29      416666   37.0  N13
569340 2026-05-29      239078   55.9  F16

[323493 rows x 4 columns]

In [27]:
# add month column
scrape_map['month'] = scrape_map['date'].dt.to_period('M').dt.to_timestamp()
scrape_map

             date product_sku  price code      month
0      2026-04-07       15438  509.0  F15 2026-04-01
3      2026-04-07      128213   89.9  F15 2026-04-01
5      2026-04-07       58038  206.0  F15 2026-04-01
14     2026-04-07       74310   73.9  F15 2026-04-01
16     2026-04-07        2908  235.0  F15 2026-04-01
...           ...         ...    ...  ...        ...
569330 2026-05-29      488467  199.0  F16 2026-05-01
569331 2026-05-29      239022   74.9  F16 2026-05-01
569333 2026-05-29      239016   49.9  F16 2026-05-01
569337 2026-05-29      416666   37.0  N13 2026-05-01
569340 2026-05-29      239078   55.9  F16 2026-05-01

[323493 rows x 5 columns]

In [28]:
# aggregate on month - product_sku level (code added in groupby so it doesnt disappear but it changes nothing)
scrape_map_agg = scrape_map.groupby(['month', 'product_sku', 'code'], as_index=False).agg({
    'price': 'mean'
})
scrape_map_agg = scrape_map_agg.sort_values(by=['product_sku', 'month'])
scrape_map_agg

           month product_sku code      price
0     2026-04-01       10019  N15  49.400000
7954  2026-05-01       10019  N15  46.650000
15543 2026-06-01       10019  N15  49.400000
22998 2026-07-01       10019  N15  49.400000
1     2026-04-01       10029  N15  54.950000
...          ...         ...  ...        ...
30267 2026-07-01        9836  F16  12.900000
7953  2026-04-01        9972  N15  47.750000
15542 2026-05-01        9972  N15  35.754545
22997 2026-06-01        9972  N15  47.811538
30268 2026-07-01        9972  N15  39.726923

[30269 rows x 4 columns]

In [29]:
# adding prices from previous month
scrape_map_agg['price_prev'] = scrape_map_agg.groupby('product_sku')['price'].shift(1)
scrape_map_agg['month_prev'] = scrape_map_agg.groupby('product_sku')['month'].shift(1)

# if month and month_prev +1 don't match, than previous price is none
is_exact_previous_month = (scrape_map_agg['month_prev'] + pd.DateOffset(months=1)) == scrape_map_agg['month']

scrape_map_agg.loc[~is_exact_previous_month, 'price_prev'] = None
scrape_map_agg

           month product_sku code      price  price_prev month_prev
0     2026-04-01       10019  N15  49.400000         NaN        NaT
7954  2026-05-01       10019  N15  46.650000   49.400000 2026-04-01
15543 2026-06-01       10019  N15  49.400000   46.650000 2026-05-01
22998 2026-07-01       10019  N15  49.400000   49.400000 2026-06-01
1     2026-04-01       10029  N15  54.950000         NaN        NaT
...          ...         ...  ...        ...         ...        ...
30267 2026-07-01        9836  F16  12.900000   12.900000 2026-06-01
7953  2026-04-01        9972  N15  47.750000         NaN        NaT
15542 2026-05-01        9972  N15  35.754545   47.750000 2026-04-01
22997 2026-06-01        9972  N15  47.811538   35.754545 2026-05-01
30268 2026-07-01        9972  N15  39.726923   47.811538 2026-06-01

[30269 rows x 6 columns]

In [30]:
# price index = price / price from prevoius month
scrape_map_agg['price_index'] = scrape_map_agg['price'] / scrape_map_agg['price_prev']
scrape_map_agg = scrape_map_agg.drop(columns=['month_prev'])
scrape_map_agg.dropna(subset=['price_index'], inplace=True)
scrape_map_agg

           month product_sku code      price  price_prev  price_index
7954  2026-05-01       10019  N15  46.650000   49.400000     0.944332
15543 2026-06-01       10019  N15  49.400000   46.650000     1.058950
22998 2026-07-01       10019  N15  49.400000   49.400000     1.000000
7955  2026-05-01       10029  N15  54.950000   54.950000     1.000000
15544 2026-06-01       10029  N15  54.950000   54.950000     1.000000
...          ...         ...  ...        ...         ...          ...
22996 2026-06-01        9836  F16  12.900000   12.900000     1.000000
30267 2026-07-01        9836  F16  12.900000   12.900000     1.000000
15542 2026-05-01        9972  N15  35.754545   47.750000     0.748786
22997 2026-06-01        9972  N15  47.811538   35.754545     1.337216
30268 2026-07-01        9972  N15  39.726923   47.811538     0.830907

[22298 rows x 6 columns]

In [31]:
# merge scrape data with weights and add final code for MoM nowcast
scrape_map_agg_w = pd.merge(scrape_map_agg, weights, how='left', on=['code','month'])
scrape_map_agg_w['final_code'] = scrape_map_agg_w['code'].str[0]
scrape_map_agg_w

,month,product_sku,code,price,price_prev,price_index,weight,final_code
0,2026-05-01,10019,N15,46.650000,49.400000,0.944332,0.006471,N
1,2026-06-01,10019,N15,49.400000,46.650000,1.058950,0.006471,N
2,2026-07-01,10019,N15,49.400000,49.400000,1.000000,0.006471,N
3,2026-05-01,10029,N15,54.950000,54.950000,1.000000,0.006471,N
4,2026-06-01,10029,N15,54.950000,54.950000,1.000000,0.006471,N
...,...,...,...,...,...,...,...,...
22293,2026-06-01,9836,F16,12.900000,12.900000,1.000000,0.000622,F
22294,2026-07-01,9836,F16,12.900000,12.900000,1.000000,0.000622,F
22295,2026-05-01,9972,N15,35.754545,47.750000,0.748786,0.006471,N
22296,2026-06-01,9972,N15,47.811538,35.754545,1.337216,0.006471,N
22297,2026-07-01,9972,N15,39.726923,47.811538,0.830907,0.006471,N

In [32]:
# final results
final_df = scrape_map_agg_w.groupby(['month', 'final_code'], as_index=False).agg({
    'price_index': lambda x: np.exp(np.log(x).mean())     # if you want geo mean -> lambda x: np.exp(np.log(x).mean())     'mean'
})

final_df['price_index'] = final_df['price_index'] * 100
final_df

       month final_code  price_index
0 2026-05-01          F   101.248415
1 2026-05-01          N   103.717218
2 2026-05-01          S   100.000000
3 2026-06-01          F    99.766740
4 2026-06-01          N    99.739424
5 2026-06-01          S   100.000000
6 2026-07-01          F   100.459179
7 2026-07-01          N    99.887162
8 2026-07-01          S   100.000000

**Fuel cod integral**

In [13]:
import pandas as pd
fuel = pd.read_excel(r'/content/sample_data/fuelo_scrape.xlsx')
fuel['Date'] = pd.to_datetime(
    fuel['Date'],
    format='%d.%m.%Y'
)
cols = [
    'Unleaded 95 (l)',
    'Diesel (l)',
    'LPG (l)'
]
for col in cols:

    fuel[col] = (
        fuel[col]
        .astype(str)
        .str.replace('€', '', regex=False)
        .str.replace(',', '.', regex=False)
        .str.strip()
    )
    fuel[col] = pd.to_numeric(fuel[col], errors='coerce')

fuel = fuel.melt(
    id_vars='Date',
    var_name='fuel_type',
    value_name='price'
)

fuel['month'] = fuel['Date'].dt.to_period('M').dt.to_timestamp()
monthly_price = (
    fuel
    .groupby('month', as_index=False)
    .agg(avg_price=('price', 'mean'))
)

monthly_price['avg_price_prev'] = monthly_price['avg_price'].shift(1)
monthly_price['month_prev'] = monthly_price['month'].shift(1)

mask = (
    monthly_price['month_prev'] +
    pd.DateOffset(months=1)
) == monthly_price['month']

monthly_price.loc[~mask, 'avg_price_prev'] = pd.NA

monthly_price['price_index'] = (
    monthly_price['avg_price'] /
    monthly_price['avg_price_prev']
) * 100

final_fuel = monthly_price[['month', 'avg_price', 'price_index']]
print(final_fuel)

       month  avg_price  price_index
0 2026-03-01   1.076437          NaN
1 2026-04-01   1.287111   119.571454
2 2026-05-01   1.266774    98.419956
3 2026-06-01   1.195376    94.363806
4 2026-07-01   1.169770    97.857894

# **Modelul lui Lucas **

In [17]:
# now fuel
fuel = pd.read_excel(r'/content/sample_data/fuelo_scrape.xlsx')
fuel['Date'] = pd.to_datetime(fuel['Date'], format = '%d.%m.%Y')
fuel

cols_to_fix = ['Unleaded 95 (l)', 'Diesel (l)', 'LPG (l)']

for col in cols_to_fix:
    # remove € sign
    fuel[col] = fuel[col].astype(str).str.replace('€', '').str.strip()

    # replace , -> .
    fuel[col] = fuel[col].str.replace(',', '.')

    # change it to numeric
    fuel[col] = pd.to_numeric(fuel[col], errors='coerce')

fuel


fuel = fuel.melt(id_vars=['Date'], var_name='fuel_type', value_name='price')   # transform data from wide to long
fuel

fuel['month'] = fuel['Date'].dt.to_period('M').dt.to_timestamp()
fuel

fuel_agg = fuel.groupby(['month', 'fuel_type'], as_index=False).agg({'price':'mean'})
fuel_agg


# adding prices from previous month
fuel_agg['price_prev'] = fuel_agg.groupby('fuel_type')['price'].shift(1)
fuel_agg['month_prev'] = fuel_agg.groupby('fuel_type')['month'].shift(1)

# if month and month_prev +1 don't match, than previous price is none
is_exact_previous_month = (fuel_agg['month_prev'] + pd.DateOffset(months=1)) == fuel_agg['month']

fuel_agg.loc[~is_exact_previous_month, 'price_prev'] = None
fuel_agg


fuel_agg['price_index'] = fuel_agg['price'] / fuel_agg['price_prev'] * 100
fuel_agg


final_fuel = fuel_agg.groupby(['month'], as_index=False).agg({'price_index': 'mean'})
final_fuel

       month  price_index
0 2026-03-01          NaN
1 2026-04-01   119.518156
2 2026-05-01    98.887764
3 2026-06-01    95.008817
4 2026-07-01    97.868730

In [11]:
# now fuel
fuel = pd.read_excel(r'/content/sample_data/fuelo_scrape.xlsx')
fuel['Date'] = pd.to_datetime(fuel['Date'], format = '%d.%m.%Y')
fuel

          Date Unleaded 95 (l) Diesel (l) LPG (l)
0   2026-03-03          1,18 €     1,03 €  0,62 €
1   2026-03-04          1,18 €     1,03 €  0,62 €
2   2026-03-05          1,18 €     1,03 €  0,62 €
3   2026-03-06          1,18 €     1,03 €  0,62 €
4   2026-03-07          1,18 €     1,03 €  0,62 €
..         ...             ...        ...     ...
145 2026-07-25          1,47 €     1,44 €  0,78 €
146 2026-07-26          1,47 €     1,44 €  0,78 €
147 2026-07-27          1,47 €     1,44 €  0,78 €
148 2026-07-28          1,50 €     1,49 €  0,78 €
149 2026-07-29          1,50 €     1,50 €  0,78 €

[150 rows x 4 columns]

In [3]:
cols_to_fix = ['Unleaded 95 (l)', 'Diesel (l)', 'LPG (l)']

for col in cols_to_fix:
    # remove € sign
    fuel[col] = fuel[col].astype(str).str.replace('€', '').str.strip()

    # replace , -> .
    fuel[col] = fuel[col].str.replace(',', '.')

    # change it to numeric
    fuel[col] = pd.to_numeric(fuel[col], errors='coerce')

fuel

          Date  Unleaded 95 (l)  Diesel (l)  LPG (l)
0   2026-03-03             1.18        1.03     0.62
1   2026-03-04             1.18        1.03     0.62
2   2026-03-05             1.18        1.03     0.62
3   2026-03-06             1.18        1.03     0.62
4   2026-03-07             1.18        1.03     0.62
..         ...              ...         ...      ...
145 2026-07-25             1.47        1.44     0.78
146 2026-07-26             1.47        1.44     0.78
147 2026-07-27             1.47        1.44     0.78
148 2026-07-28             1.50        1.49     0.78
149 2026-07-29             1.50        1.50     0.78

[150 rows x 4 columns]

In [4]:
fuel = fuel.melt(id_vars=['Date'], var_name='fuel_type', value_name='price')   # transform data from wide to long
fuel

          Date        fuel_type  price
0   2026-03-03  Unleaded 95 (l)   1.18
1   2026-03-04  Unleaded 95 (l)   1.18
2   2026-03-05  Unleaded 95 (l)   1.18
3   2026-03-06  Unleaded 95 (l)   1.18
4   2026-03-07  Unleaded 95 (l)   1.18
..         ...              ...    ...
445 2026-07-25          LPG (l)   0.78
446 2026-07-26          LPG (l)   0.78
447 2026-07-27          LPG (l)   0.78
448 2026-07-28          LPG (l)   0.78
449 2026-07-29          LPG (l)   0.78

[450 rows x 3 columns]

In [5]:
fuel['month'] = fuel['Date'].dt.to_period('M').dt.to_timestamp()
fuel

          Date        fuel_type  price      month
0   2026-03-03  Unleaded 95 (l)   1.18 2026-03-01
1   2026-03-04  Unleaded 95 (l)   1.18 2026-03-01
2   2026-03-05  Unleaded 95 (l)   1.18 2026-03-01
3   2026-03-06  Unleaded 95 (l)   1.18 2026-03-01
4   2026-03-07  Unleaded 95 (l)   1.18 2026-03-01
..         ...              ...    ...        ...
445 2026-07-25          LPG (l)   0.78 2026-07-01
446 2026-07-26          LPG (l)   0.78 2026-07-01
447 2026-07-27          LPG (l)   0.78 2026-07-01
448 2026-07-28          LPG (l)   0.78 2026-07-01
449 2026-07-29          LPG (l)   0.78 2026-07-01

[450 rows x 4 columns]

In [6]:
fuel_agg = fuel.groupby(['month', 'fuel_type'], as_index=False).agg({'price':'mean'})
fuel_agg

        month        fuel_type     price
0  2026-03-01       Diesel (l)  1.256207
1  2026-03-01          LPG (l)  0.676207
2  2026-03-01  Unleaded 95 (l)  1.296897
3  2026-04-01       Diesel (l)  1.595333
4  2026-04-01          LPG (l)  0.803000
5  2026-04-01  Unleaded 95 (l)  1.463000
6  2026-05-01       Diesel (l)  1.476129
7  2026-05-01          LPG (l)  0.805806
8  2026-05-01  Unleaded 95 (l)  1.518387
9  2026-06-01       Diesel (l)  1.345161
10 2026-06-01          LPG (l)  0.795161
11 2026-06-01  Unleaded 95 (l)  1.445806
12 2026-07-01       Diesel (l)  1.317241
13 2026-07-01          LPG (l)  0.778621
14 2026-07-01  Unleaded 95 (l)  1.413448

In [7]:
# adding prices from previous month
fuel_agg['price_prev'] = fuel_agg.groupby('fuel_type')['price'].shift(1)
fuel_agg['month_prev'] = fuel_agg.groupby('fuel_type')['month'].shift(1)

# if month and month_prev +1 don't match, than previous price is none
is_exact_previous_month = (fuel_agg['month_prev'] + pd.DateOffset(months=1)) == fuel_agg['month']

fuel_agg.loc[~is_exact_previous_month, 'price_prev'] = None
fuel_agg

        month        fuel_type     price  price_prev month_prev
0  2026-03-01       Diesel (l)  1.256207         NaN        NaT
1  2026-03-01          LPG (l)  0.676207         NaN        NaT
2  2026-03-01  Unleaded 95 (l)  1.296897         NaN        NaT
3  2026-04-01       Diesel (l)  1.595333    1.256207 2026-03-01
4  2026-04-01          LPG (l)  0.803000    0.676207 2026-03-01
5  2026-04-01  Unleaded 95 (l)  1.463000    1.296897 2026-03-01
6  2026-05-01       Diesel (l)  1.476129    1.595333 2026-04-01
7  2026-05-01          LPG (l)  0.805806    0.803000 2026-04-01
8  2026-05-01  Unleaded 95 (l)  1.518387    1.463000 2026-04-01
9  2026-06-01       Diesel (l)  1.345161    1.476129 2026-05-01
10 2026-06-01          LPG (l)  0.795161    0.805806 2026-05-01
11 2026-06-01  Unleaded 95 (l)  1.445806    1.518387 2026-05-01
12 2026-07-01       Diesel (l)  1.317241    1.345161 2026-06-01
13 2026-07-01          LPG (l)  0.778621    0.795161 2026-06-01
14 2026-07-01  Unleaded 95 (l)  1.413448    1.445806 2026-06-01

In [8]:
fuel_agg['price_index'] = fuel_agg['price'] / fuel_agg['price_prev'] * 100
fuel_agg

        month        fuel_type     price  price_prev month_prev  price_index
0  2026-03-01       Diesel (l)  1.256207         NaN        NaT          NaN
1  2026-03-01          LPG (l)  0.676207         NaN        NaT          NaN
2  2026-03-01  Unleaded 95 (l)  1.296897         NaN        NaT          NaN
3  2026-04-01       Diesel (l)  1.595333    1.256207 2026-03-01   126.996066
4  2026-04-01          LPG (l)  0.803000    0.676207 2026-03-01   118.750637
5  2026-04-01  Unleaded 95 (l)  1.463000    1.296897 2026-03-01   112.807764
6  2026-05-01       Diesel (l)  1.476129    1.595333 2026-04-01    92.527938
7  2026-05-01          LPG (l)  0.805806    0.803000 2026-04-01   100.349496
8  2026-05-01  Unleaded 95 (l)  1.518387    1.463000 2026-04-01   103.785858
9  2026-06-01       Diesel (l)  1.345161    1.476129 2026-05-01    91.127622
10 2026-06-01          LPG (l)  0.795161    0.805806 2026-05-01    98.678943
11 2026-06-01  Unleaded 95 (l)  1.445806    1.518387 2026-05-01    95.219885
12 2026-07-01       Diesel (l)  1.317241    1.345161 2026-06-01    97.924419
13 2026-07-01          LPG (l)  0.778621    0.795161 2026-06-01    97.919843
14 2026-07-01  Unleaded 95 (l)  1.413448    1.445806 2026-06-01    97.761929

In [9]:
final_fuel = fuel_agg.groupby(['month'], as_index=False).agg({'price_index': 'mean'})
final_fuel

       month  price_index
0 2026-03-01          NaN
1 2026-04-01   119.518156
2 2026-05-01    98.887764
3 2026-06-01    95.008817
4 2026-07-01    97.868730